available_models: ["gpt-4o-mini", "gpt-4o"]

info:
  gpt-4o:
    name: GPT-4o
    description: "Powerful model for complex tasks with optimized performance"
    max_tokens: 8192
    temperature: 0.7
  gpt-4o-mini:
    name: GPT-4o-mini
    description: "Lightweight version of GPT-4 for quick responses"
    max_tokens: 4096
    temperature: 0.7
